#!/usr/bin/env sh

set -e

git config --global user.email "fkretschmar@googlemail.com"
git config --global user.name "floydkretschmar"
git fetch origin
git switch -c gh-pages origin/gh-pages

# if it exists save the CNAME as it does not get generated by npm build
if [ -e CNAME ]; then
    mv CNAME ../dist/
fi

rm -r *
cp -r ../dist/* .

# only try to commit the changes if there actually are any
if [ -n "$(git diff --exit-code)" ]; then
    git add -A
    git diff
    git commit -m "new deployment"
    git push
fi