name: Build portfolio website

on:
  push:
    branches:
      - main
      
permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node dependencies
        run: npm install

      - name: Build source
        run: npm run build

      - name: Push source to github pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy