name: Deploy portfolio website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build source
        run: |
          npm run build

      - name: Deploy to github pages
        run: |
          cd dist
          git config --global user.email "fkretschmar@googlemail.com"
          git config --global user.name "floydkretschmar"
          git init 
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout -b gh-pages
          git add -A
          git commit -m "new deployment"
          git push