name: Deploy portfolio website

on:
  push:
    branches:
      - main
      
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build source
        run: |
          npm run build

      - name: Deploy to github pages
        run: |
          cd dist
          git config --global user.email "fkretschmar@googlemail.com"
          git config --global user.name "floydkretschmar"
          git init 
          git add -A
          git commit -m "new deployment"
          git push git@github.com:floydkretschmar/portfolio.git master:gh-pages